apiVersion: v1 
kind: Service 
metadata: 
  name: dor-admission-webhook-svc 
  namespace: default 
spec: 
  ports: 
    - port: 443 
      targetPort: 8443 
  selector: 
    app: dor-admission-webhook 

